#!/usr/bin/env bash
# Bash script to install nginx on web-01

set -e  # Exit if any command fails

# Make sure the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

apt-get update -y
apt-get install nginx -y

# Set up the web root with "Hello World!"
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html

# Restart nginx using service command
service nginx restart
