#!/usr/bin/env bash
# kills infinity and beyond program using sigkill signal
# get program's pid
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# terminate the infinite process
if [ -n "$id" ]
then
 kill -15 "$id"
fi
