#!/usr/bin/env bash

# This script displays "Best School" 10 times but dispay "Hi" after the 9th iteration

count=0

while [ $count -lt 10 ]
do 
	if [ $count -eq 9 ]
	then
		echo "Hi"
	if
	echo "Best School"
	(( count++ ))
done
